### ISSUE TITLE
Contribuir sem baixar todos os logos

### ISSUE THREAD

**Issue by calderaricaio** [tiagoporto/svg-music-logos#28]
Oi tudo bem? Queria tirar uma dúvida, existe alguma forma de contribuir com esse projeto sem ter que baixar todos os logos dele? Pensei nisso pois conforme for aumentando mais e mais para cada nova pessoa que quiser ajudar teria que baixar toda vez os conteúdos novamente, teria alguma forma melhor de poder ajudar sem precisar baixar e subir tudo?

**Comment by tiagoporto** [comment]
Olá Caio, então, acredito que quando eles estiverem em SVG vai ficar bem mais leve. Por enquanto, tem muitos logos que separei para converter que estão em outros formatos e realmente estão pesando, deixei eles em outra branch. Obrigado pela dica e pelos PRs assim que sobrar um tempinho publico eles.

Abraço

**Comment by calderaricaio** [comment]
Ahh, entendi, legal! Que bom que pude ajudar de alguma forma, ainda não manjo muito de git. Abraço!
