### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by tiagoporto** [tiagoporto/svg-music-logos#7]

**Comment by kvnol** [comment]
cara, tive uma ideia. o que acha?
![svgmusiclogos](https://cloud.githubusercontent.com/assets/3299130/18236374/a9efbcf8-72fb-11e6-9a9f-555ee832a1d1.png)

**Comment by tiagoporto** [comment]
Opa @kvnol, obrigado por trabalhar em uma logo para o projeto. 
Olha eu sinto que tá faltando alguma coisa que de um toque elegante ou futurista. Achei que os elementos estão soltos. Não se prenda a cor do site, pode usar a(s) cor(es) que quiser.
A tipografia está precisando de um refinamento, o vetor está irregular em alguns pontos e algumas compensações óticas são necessárias. Por exemplo o G parece mais fino que o S e o V. As letras me parecem condensadas demais. Precisa de um ajuste de kerning entr eo VG.

**Comment by kvnol** [comment]
@tiagoporto Sim, também vejo que precisam de ajustes de kerning.

**Comment by tiagoporto** [comment]
Acessa esse [arquivo](https://github.com/tiagoporto/svg-music-logos/blob/master/dist/img/logos/svg-music-logos.ai), comecei a fazer uns estudos para a logo.

**Comment by kvnol** [comment]
Esse com gradiente é lindo.
![capture](https://cloud.githubusercontent.com/assets/3299130/18259752/dfad0626-73bd-11e6-9b1b-2551bbd79d6b.PNG)

**Comment by tiagoporto** [comment]
hehehe ainda não gostei muito.

**Comment by kvnol** [comment]
O contraste com o amarelo e com o texto nao está legal, mas a ideia do gradiente é massa. Vou dar uma repensada aqui em cima disso.

**Comment by tiagoporto** [comment]
Suggestion by @SrishtiSengupta 
![svgmusic](https://user-images.githubusercontent.com/3688905/31242107-5fa3de22-a9dc-11e7-8f80-3deff36fc460.png)

**Comment by tiagoporto** [comment]
@podrivo Help?

**Comment by benjaminchazelle** [comment]
Here is my proposal =)

![image](https://user-images.githubusercontent.com/15939384/31690105-fc5c97c2-b391-11e7-9fa2-a01da53393a4.png)
